version: 1.0.{build}.{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
os: Windows Server 2012 R2
clone_depth: 50
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
- gradlew.bat wrapper
- gradlew.bat dependencies
nuget:
  disable_publish_on_pr: true
build_script:
- gradlew.bat shadowJar
test_script:
- gradlew.bat test
artifacts:
- path: build/libs/*.jar